nodeLinker: pnpm
enableTelemetry: false
enableScripts: true
packageExtensions:
  "@preact/preset-vite@*":
    dependencies:
      "@babel/core": "*"
  "astro@*":
    peerDependencies:
      "@astrojs/check": "*"
      typescript: "*"
    peerDependenciesMeta:
      "@astrojs/check":
        optional: true
      typescript:
        optional: true
